spring.application.name=task-api

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mengaktifkan Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Konfigurasi Database H2 agar tidak error saat diakses
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port =9000

# Logger
logging.level.root=INFO
logging.level.com.belajar.task_api=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.file.name=logs/application.log
# %d{yyyy-MM-dd} artinya file akan di-roll setiap hari
logging.logback.rollingpolicy.file-name-pattern=logs/application-%d{yyyy-MM-dd}.log
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=2GB
app.auth.simulated-username=atkinson
app.auth.simulated-password=password123
app.auth.simulated-role=OPERATOR
app.rate-limit.capacity=2
app.rate-limit.duration-in-seconds=10


# Circuit Breaker backendA configuration
resilience4j.circuitbreaker.instances.backendA.sliding-window-size=5
resilience4j.circuitbreaker.instances.backendA.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.backendA.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.backendA.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.backendA.automatic-transition-from-open-to-half-open-enabled=true